### ISSUE TITLE
Not work for version 2.21 and later

### ISSUE THREAD

**Issue by qianlvable** [fjenett/Guido#11]
I try to run the examples on the Processing 2.21 and 3.0(Windows 64-bit), and it got error message showing below:
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
    at java.util.regex.Pattern.error(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at java.util.regex.Pattern.<init>(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at java.lang.String.replaceAll(Unknown Source)
    at de.bezier.mode.javascript.JavaScriptBuild.build(Unknown Source)
    at de.bezier.mode.javascript.JavaScriptBuild.export(Unknown Source)
    at de.bezier.mode.javascript.JavaScriptMode.handleExport(Unknown Source)
    at de.bezier.mode.javascript.JavaScriptEditor.handleExport(Unknown Source)
    at de.bezier.mode.javascript.JavaScriptEditor.serverStarted(Unknown Source)
    at de.bezier.mode.javascript.BasicServer.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by fjenett** [comment]
Have to check … i think the newer Processing versions have modifications to the preprocessing that cause these.

**Comment by q2dg** [comment]
...

**Comment by fjenett** [comment]
Tx!

**Comment by q2dg** [comment]
Well...let's forget this library, then

**Comment by haschdl** [comment]
hi Florian @fjenett ! You probably spent a lot of time developing the library, and likely it helped a lot of people! Since the library doesn't work with new versions of Processing, would it be possible to put a warning in your README that the library is no longer maintained, and perhaps ask Processing to remove it from the repository?
