### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by ForwardMetrics** [fjenett/Guido#14]
Hi,

I get the error below periodically. Over time Processing runs out of memory (garbage collection?). I am using a modified version of Button example. Great library by the way.

java.lang.NullPointerException
    at de.bezier.guido.Interactive$1.run(Unknown Source)

Scott

**Comment by fjenett** [comment]
Hey, can you give a little more information? I think a sketch showing the problem would be helpful. Thanks.

**Comment by ForwardMetrics** [comment]
Hi,

I resolved the issue by refactoring the code into a new project.

I was wondering if an update would be made that included the Remove method?

Also, I ran into a problem where the callback event MousePressed is being called. This may be caused by the depth of nesting as I’m building compound UIs. Is there a limit on the number of objects?

Thanks,

Scott

**Comment by YishiO-O** [comment]
@ForwardMetrics 

I'm having the same issue now.

> java.lang.NullPointerException
> at de.bezier.guido.Interactive$1.run(Unknown Source)

Could you share how you solve the problem with more details?
